# Generated by Django 3.1.1 on 2020-09-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruserapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
