# Generated by Django 3.1.1 on 2020-09-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationapp', '0002_auto_20200911_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='viewed_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
